"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { api, ApiRequestError } from "@/lib/api";
import { ConfirmDialog } from "@/components/admin/ConfirmDialog";
import { EmptyState, ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";
import { DataTable } from "@/components/admin/DataTable";
import { ParentForm, type ParentFormValues } from "@/components/admin/ParentForm";
import type { Parent } from "@/types";

export default function ParentsPage() {
  const router = useRouter(); const [parents, setParents] = useState<Parent[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<Parent | null>(null); const [modal, setModal] = useState(false); const [confirm, setConfirm] = useState<Parent | null>(null); const [busy, setBusy] = useState(false); const [errors, setErrors] = useState<Record<string, string[]> | undefined>(); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await api.get<{ parents: Parent[] }>("/parents"); setParents(result.parents); } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : "Unable to load parents."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => { const query = search.toLowerCase(); return parents.filter((parent) => !query || parent.name.toLowerCase().includes(query) || parent.email?.toLowerCase().includes(query)); }, [parents, search]);
  async function save(values: ParentFormValues) { setBusy(true); setErrors(undefined); try { const payload = { ...values, role: "parent" as const, ...(values.password ? {} : { password: undefined }) }; if (selected) { const result = await api.put<{ user: Parent }>(`/users/${selected.id}`, payload); setParents((current) => current.map((item) => item.id === selected.id ? { ...item, ...result.user } : item)); setNotice("Parent updated successfully."); } else { const result = await api.post<{ user: Parent }>("/users", payload); setParents((current) => [{ ...result.user, children: [] }, ...current]); setNotice("Parent added successfully."); } setModal(false); } catch (cause) { setErrors({ ...(cause instanceof ApiRequestError ? cause.details?.errors : {}), _form: [cause instanceof ApiRequestError ? cause.message : "Unable to save parent."] }); } finally { setBusy(false); } }
  async function remove() { if (!confirm) return; setBusy(true); try { await api.delete(`/users/${confirm.id}`); setParents((current) => current.filter((item) => item.id !== confirm.id)); setConfirm(null); setNotice("Parent deleted successfully."); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : "Unable to delete parent."); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading parents..." />; if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  return <><section className="admin-page-heading"><div><p className="kicker">People directory</p><h2>Parents</h2><p>Manage parent accounts and their linked children.</p></div><button className="primary-button compact-button" onClick={() => { setSelected(null); setErrors(undefined); setModal(true); }}><Plus size={17} />Add parent</button></section>{notice && <Notice message={notice} />}<section className="list-card"><div className="list-toolbar"><label className="search-input"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name or email" aria-label="Search parents" /></label></div>{filtered.length ? <DataTable columns={[{ label: "Parent", key: "parent" }, { label: "Email", key: "email" }, { label: "Children", key: "children" }, { label: "Actions", key: "actions" }]} rows={filtered.map((parent) => ({ ...parent, parent: <div className="school-cell"><span className="school-avatar">{parent.name.charAt(0).toUpperCase()}</span><div><strong>{parent.name}</strong><small>{parent.role.replace("_", " ")}</small></div></div>, email: parent.email, children: `${parent.children?.length ?? 0} linked`, actions: <div className="row-actions"><button onClick={() => router.push(`/school/parents/${parent.id}`)} aria-label={`View ${parent.name}`}><Eye size={16} /></button><button onClick={() => { setSelected(parent); setErrors(undefined); setModal(true); }} aria-label={`Edit ${parent.name}`}><Pencil size={16} /></button><button className="row-danger" onClick={() => setConfirm(parent)} aria-label={`Delete ${parent.name}`}><Trash2 size={16} /></button></div> }))} /> : <EmptyState title="No parents found" copy={parents.length ? "Try a different search." : "Add a parent account to begin."} />}</section>{modal && <div className="dialog-backdrop"><div className="form-dialog"><div className="dialog-header"><p className="kicker">{selected ? "Edit account" : "New account"}</p><h2>{selected ? "Edit parent" : "Add a parent"}</h2></div><ParentForm parent={selected} busy={busy} errors={errors} onSubmit={save} onCancel={() => setModal(false)} /></div></div>}{confirm && <ConfirmDialog title={`Delete ${confirm.name}?`} copy="This removes the parent account and its parent relationships. This action cannot be undone." busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => void remove()} />}</>;
}
