"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, Filter, Pencil, Plus, School as SchoolIcon, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { api, ApiRequestError } from "@/lib/api";
import { ConfirmDialog } from "@/components/admin/ConfirmDialog";
import { EmptyState, ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";
import { SchoolForm, type SchoolFormValues } from "@/components/admin/SchoolForm";
import { SearchInput } from "@/components/admin/SearchInput";
import { DataTable } from "@/components/admin/DataTable";
import type { School } from "@/types";

export default function SchoolsPage() {
  const router = useRouter();
  const [schools, setSchools] = useState<School[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [modal, setModal] = useState<"create" | "edit" | null>(null); const [selected, setSelected] = useState<School | null>(null); const [confirm, setConfirm] = useState<School | null>(null); const [busy, setBusy] = useState(false); const [formErrors, setFormErrors] = useState<Record<string, string[]> | undefined>(); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await api.get<{ schools: School[] }>("/schools"); setSchools(result.schools); } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : "Unable to load schools."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => schools.filter((school) => { const query = search.toLowerCase(); const matchesSearch = !query || school.name.toLowerCase().includes(query) || school.code.toLowerCase().includes(query); const matchesStatus = status === "all" || (status === "active" ? school.is_active : !school.is_active); return matchesSearch && matchesStatus; }), [schools, search, status]);
  function openCreate() { setSelected(null); setFormErrors(undefined); setModal("create"); }
  function openEdit(school: School) { setSelected(school); setFormErrors(undefined); setModal("edit"); }
  async function save(values: SchoolFormValues) { setBusy(true); setFormErrors(undefined); try { if (selected) { const schoolValues = { name: values.name, code: values.code, email: values.email, phone: values.phone, address: values.address, logo: values.logo, is_active: values.is_active }; const result = await api.put<{ school: School }>(`/schools/${selected.id}`, schoolValues); setSchools((current) => current.map((item) => item.id === selected.id ? result.school : item)); setNotice("School updated successfully."); } else { const result = await api.post<{ school: School }>("/schools", values); setSchools((current) => [result.school, ...current]); setNotice("School created successfully."); } setModal(null); } catch (cause) { if (cause instanceof ApiRequestError) setFormErrors({ ...(cause.details?.errors ?? {}), _form: [cause.message] }); else setFormErrors({ _form: ["Unable to save this school."] }); } finally { setBusy(false); } }
  async function remove() { if (!confirm) return; setBusy(true); try { await api.delete(`/schools/${confirm.id}`); setSchools((current) => current.filter((item) => item.id !== confirm.id)); setNotice("School deleted successfully."); setConfirm(null); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : "Unable to delete this school."); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading schools..." />;
  if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  return <><section className="admin-page-heading"><div><p className="kicker">System directory</p><h2>Schools</h2><p>Manage the schools that make up your network.</p></div><button className="primary-button compact-button" onClick={openCreate}><Plus size={17} />Add school</button></section>{notice && <Notice message={notice} />}<section className="list-card"><div className="list-toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Search by name or code" /><label className="filter-select"><Filter size={16} /><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter school status"><option value="all">All statuses</option><option value="active">Active only</option><option value="inactive">Inactive only</option></select></label></div>{filtered.length ? <DataTable columns={[{ label: "School", key: "school" }, { label: "Code", key: "code" }, { label: "Contact", key: "contact" }, { label: "Status", key: "status" }, { label: "Actions", key: "actions" }]} rows={filtered.map((school) => ({ ...school, school: <div className="school-cell"><span className="school-avatar"><SchoolIcon size={16} /></span><div><strong>{school.name}</strong><small>{school.email || "No email provided"}</small></div></div>, code: <span className="code-text">{school.code}</span>, contact: <span className="muted-cell">{school.phone || "—"}</span>, status: <span className={`status-badge ${school.is_active ? "status-active" : "status-inactive"}`}>{school.is_active ? "Active" : "Inactive"}</span>, actions: <div className="row-actions"><button onClick={() => router.push(`/super-admin/schools/${school.id}`)} aria-label={`View ${school.name}`}><Eye size={16} /></button><button onClick={() => openEdit(school)} aria-label={`Edit ${school.name}`}><Pencil size={16} /></button><button className="row-danger" onClick={() => setConfirm(school)} aria-label={`Delete ${school.name}`}><Trash2 size={16} /></button></div> }))} /> : <EmptyState title="No schools match" copy={schools.length ? "Try a different search or status filter." : "Create your first school to populate the directory."} />}</section>{modal && <div className="dialog-backdrop"><div className="form-dialog"><div className="dialog-header"><div><p className="kicker">{selected ? "Edit record" : "New record"}</p><h2>{selected ? "Edit school" : "Add a school"}</h2></div><button className="dialog-close" onClick={() => setModal(null)} aria-label="Close school form">×</button></div><SchoolForm school={selected} busy={busy} errors={formErrors} onSubmit={save} onCancel={() => setModal(null)} /></div></div>}{confirm && <ConfirmDialog title={`Delete ${confirm.name}?`} copy="This may affect users and related school data through the backend's cascading relationships. This action cannot be undone." busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => void remove()} />}</>;
}
