"use client";
import { useCallback, useEffect, useState } from "react";
import { api, ApiRequestError } from "@/lib/api";
import { ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";
import type { AcademicYear, SchoolClass, Section, Subject, Student } from "@/types";
export default function BulkSubjectAssignmentsPage() {
  const [years,setYears]=useState<AcademicYear[]>([]); const [classes,setClasses]=useState<SchoolClass[]>([]); const [sections,setSections]=useState<Section[]>([]); const [subjects,setSubjects]=useState<Subject[]>([]); const [students,setStudents]=useState<Student[]>([]); const [yearId,setYearId]=useState(""); const [classId,setClassId]=useState(""); const [sectionId,setSectionId]=useState(""); const [subjectIds,setSubjectIds]=useState<string[]>([]); const [studentIds,setStudentIds]=useState<string[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [y,c,s,u]=await Promise.all([api.get<{academic_years:AcademicYear[]}>("/academic-years"),api.get<{classes:SchoolClass[]}>("/classes"),api.get<{sections:Section[]}>("/sections"),api.get<{subjects:Subject[]}>("/subjects")]);setYears(y.academic_years);setClasses(c.classes);setSections(s.sections);setSubjects(u.subjects);}catch(cause){setError(cause instanceof ApiRequestError?cause.message:"Unable to load assignment options.");}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function loadStudents(){if(!classId)return;try{const result=await api.get<{students:Student[]}>(`/students?class_id=${classId}${sectionId?`&section_id=${sectionId}`:""}`);setStudents(result.students);setStudentIds([]);}catch(cause){setNotice(cause instanceof ApiRequestError?cause.message:"Unable to load students.");}}
  async function assign(){setBusy(true);try{const result=await api.post<{message:string;created:number}>("/student-subject-assignments/bulk",{academic_year_id:yearId?Number(yearId):null,subject_ids:subjectIds.map(Number),student_ids:studentIds.map(Number)});setNotice(`${result.message} (${result.created} new assignments)`);}catch(cause){setNotice(cause instanceof ApiRequestError?cause.message:"Unable to assign subjects.");}finally{setBusy(false);}}
  if(loading)return <LoadingState label="Loading assignment options..." />;if(error)return <ErrorState message={error} onRetry={()=>void load()} />;
  const visibleSections=sections.filter((section)=>!classId||String(section.school_class_id)===classId);
  return <><section className="admin-page-heading"><div><p className="kicker">Academic setup</p><h2>Bulk Student Subject Assignment</h2><p>Assign selected subjects to students in a class and section.</p></div></section>{notice&&<Notice message={notice}/>}<section className="list-card"><div className="form-grid"><label>Academic year<select value={yearId} onChange={e=>setYearId(e.target.value)}><option value="">Select year</option>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>Class<select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Select class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Section<select value={sectionId} onChange={e=>setSectionId(e.target.value)}><option value="">All sections</option>{visibleSections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><button className="secondary-button" onClick={()=>void loadStudents()} disabled={!classId}>Load students</button>{students.length>0&&<div className="form-grid"><label>Subjects<select multiple value={subjectIds} onChange={e=>setSubjectIds(Array.from(e.target.selectedOptions,option=>option.value))}>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Students<select multiple value={studentIds} onChange={e=>setStudentIds(Array.from(e.target.selectedOptions,option=>option.value))}>{students.map(s=><option key={s.id} value={s.id}>{s.user?.name||s.student_id||`Student #${s.id}`}</option>)}</select></label></div>}<button className="primary-button" onClick={()=>void assign()} disabled={busy||!subjectIds.length||!studentIds.length}>{busy?"Assigning...":"Assign selected subjects"}</button></section></>;
}
