"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Search, Trash2 } from "lucide-react";
import { api, ApiRequestError } from "@/lib/api";
import { ClassForm, type ClassFormValues } from "@/components/admin/ClassForm";
import { ConfirmDialog } from "@/components/admin/ConfirmDialog";
import { DataTable } from "@/components/admin/DataTable";
import { EmptyState, ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";
import type { SchoolClass } from "@/types";
export default function ClassesPage() {
  const [items, setItems] = useState<SchoolClass[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<SchoolClass | null>(null); const [confirm, setConfirm] = useState<SchoolClass | null>(null); const [busy, setBusy] = useState(false); const [modal, setModal] = useState(false); const [errors, setErrors] = useState<Record<string, string[]> | undefined>(); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await api.get<{ classes: SchoolClass[] }>("/classes"); setItems(result.classes); } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : "Unable to load classes."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => items.filter((item) => { const query = search.toLowerCase(); return !query || item.name.toLowerCase().includes(query) || item.code?.toLowerCase().includes(query); }), [items, search]);
  async function save(values: ClassFormValues) { setBusy(true); setErrors(undefined); try { const payload = { ...values, numeric_order: values.numeric_order ? Number(values.numeric_order) : null }; const result = selected ? await api.put<{ class: SchoolClass }>(`/classes/${selected.id}`, payload) : await api.post<{ class: SchoolClass }>("/classes", payload); setItems((current) => selected ? current.map((item) => item.id === selected.id ? result.class : item) : [result.class, ...current]); setModal(false); setNotice(selected ? "Class updated successfully." : "Class added successfully."); } catch (cause) { setErrors({ ...(cause instanceof ApiRequestError ? cause.details?.errors : {}), _form: [cause instanceof ApiRequestError ? cause.message : "Unable to save class."] }); } finally { setBusy(false); } }
  async function remove() { if (!confirm) return; setBusy(true); try { await api.delete(`/classes/${confirm.id}`); setItems((current) => current.filter((item) => item.id !== confirm.id)); setConfirm(null); setNotice("Class deleted successfully."); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : "Unable to delete class."); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading classes..." />; if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  return <><section className="admin-page-heading"><div><p className="kicker">Academic setup</p><h2>Classes</h2><p>Organize the grades and learning levels in your school.</p></div><button className="primary-button compact-button" onClick={() => { setSelected(null); setErrors(undefined); setModal(true); }}><Plus size={17} />Add class</button></section>{notice && <Notice message={notice} />}<section className="list-card"><div className="list-toolbar"><label className="search-input"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search class name or code" aria-label="Search classes" /></label></div>{filtered.length ? <DataTable columns={[{ label: "Class", key: "name" }, { label: "Code", key: "code" }, { label: "Order", key: "order" }, { label: "Status", key: "status" }, { label: "Actions", key: "actions" }]} rows={filtered.map((item) => ({ ...item, name: <strong>{item.name}</strong>, code: <span className="code-text">{item.code || "—"}</span>, order: item.numeric_order || "—", status: <span className={`status-badge ${item.is_active === false ? "status-inactive" : "status-active"}`}>{item.is_active === false ? "Inactive" : "Active"}</span>, actions: <div className="row-actions"><button onClick={() => { setSelected(item); setErrors(undefined); setModal(true); }} aria-label={`Edit ${item.name}`}><Pencil size={16} /></button><button className="row-danger" onClick={() => setConfirm(item)} aria-label={`Delete ${item.name}`}><Trash2 size={16} /></button></div> }))} /> : <EmptyState title="No classes found" copy={items.length ? "Try a different search." : "Add your first class to begin."} />}</section>{modal && <div className="dialog-backdrop"><div className="form-dialog"><div className="dialog-header"><p className="kicker">{selected ? "Edit record" : "New record"}</p><h2>{selected ? "Edit class" : "Add a class"}</h2></div><ClassForm schoolClass={selected} busy={busy} errors={errors} onSubmit={save} onCancel={() => setModal(false)} /></div></div>}{confirm && <ConfirmDialog title={`Delete ${confirm.name}?`} copy="Classes with related sections or students may be rejected by backend relationships." busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => void remove()} />}</>;
}
