"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Search, Trash2 } from "lucide-react";
import { api, ApiRequestError } from "@/lib/api";
import { SubjectForm, type SubjectFormValues } from "@/components/admin/SubjectForm";
import { ConfirmDialog } from "@/components/admin/ConfirmDialog";
import { DataTable } from "@/components/admin/DataTable";
import { EmptyState, ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";
import type { Subject } from "@/types";
export default function SubjectsPage() {
  const [items, setItems] = useState<Subject[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<Subject | null>(null); const [confirm, setConfirm] = useState<Subject | null>(null); const [modal, setModal] = useState(false); const [busy, setBusy] = useState(false); const [errors, setErrors] = useState<Record<string, string[]> | undefined>(); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await api.get<{ subjects: Subject[] }>("/subjects"); setItems(result.subjects); } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : "Unable to load subjects."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => items.filter((item) => { const query = search.toLowerCase(); return !query || item.name.toLowerCase().includes(query) || item.code.toLowerCase().includes(query); }), [items, search]);
  async function save(values: SubjectFormValues) { setBusy(true); setErrors(undefined); try { const result = selected ? await api.put<{ subject: Subject }>(`/subjects/${selected.id}`, values) : await api.post<{ subject: Subject }>("/subjects", values); setItems((current) => selected ? current.map((item) => item.id === selected.id ? result.subject : item) : [result.subject, ...current]); setModal(false); setNotice(selected ? "Subject updated successfully." : "Subject added successfully."); } catch (cause) { setErrors({ ...(cause instanceof ApiRequestError ? cause.details?.errors : {}), _form: [cause instanceof ApiRequestError ? cause.message : "Unable to save subject."] }); } finally { setBusy(false); } }
  async function remove() { if (!confirm) return; setBusy(true); try { await api.delete(`/subjects/${confirm.id}`); setItems((current) => current.filter((item) => item.id !== confirm.id)); setConfirm(null); setNotice("Subject deleted successfully."); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : "Unable to delete subject."); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading subjects..." />; if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  return <><section className="admin-page-heading"><div><p className="kicker">Academic setup</p><h2>Subjects</h2><p>Maintain the subjects available across your school.</p></div><button className="primary-button compact-button" onClick={() => { setSelected(null); setErrors(undefined); setModal(true); }}><Plus size={17} />Add subject</button></section>{notice && <Notice message={notice} />}<section className="list-card"><div className="list-toolbar"><label className="search-input"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search subject name or code" aria-label="Search subjects" /></label></div>{filtered.length ? <DataTable columns={[{ label: "Subject", key: "name" }, { label: "Code", key: "code" }, { label: "Description", key: "description" }, { label: "Status", key: "status" }, { label: "Actions", key: "actions" }]} rows={filtered.map((item) => ({ ...item, name: <strong>{item.name}</strong>, code: <span className="code-text">{item.code}</span>, description: <span className="muted-cell">{item.description || "—"}</span>, status: <span className={`status-badge ${item.is_active === false ? "status-inactive" : "status-active"}`}>{item.is_active === false ? "Inactive" : "Active"}</span>, actions: <div className="row-actions"><button onClick={() => { setSelected(item); setErrors(undefined); setModal(true); }} aria-label={`Edit ${item.name}`}><Pencil size={16} /></button><button className="row-danger" onClick={() => setConfirm(item)} aria-label={`Delete ${item.name}`}><Trash2 size={16} /></button></div> }))} /> : <EmptyState title="No subjects found" copy={items.length ? "Try a different search." : "Add your first subject to begin."} />}</section>{modal && <div className="dialog-backdrop"><div className="form-dialog"><div className="dialog-header"><p className="kicker">{selected ? "Edit record" : "New record"}</p><h2>{selected ? "Edit subject" : "Add a subject"}</h2></div><SubjectForm subject={selected} busy={busy} errors={errors} onSubmit={save} onCancel={() => setModal(false)} /></div></div>}{confirm && <ConfirmDialog title={`Delete ${confirm.name}?`} copy="Subjects used by academic records may be rejected by backend relationships." busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => void remove()} />}</>;
}
