"use client";

import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, BookOpen, Mail, Phone, School as SchoolIcon, UserRound } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { api, ApiRequestError } from "@/lib/api";
import { EmptyState, ErrorState, LoadingState } from "@/components/admin/AdminStates";
import type { Teacher, TeacherAssignment } from "@/types";

export default function TeacherDetailsPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [teacher, setTeacher] = useState<Teacher | null>(null); const [assignments, setAssignments] = useState<TeacherAssignment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [teacherResult, assignmentResult] = await Promise.all([api.get<{ teacher: Teacher }>(`/teachers/${id}`), api.get<{ assignments: TeacherAssignment[] }>(`/teacher-assignments`)]); setTeacher(teacherResult.teacher); setAssignments(assignmentResult.assignments.filter((item) => item.teacher_id === Number(id))); } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : "Unable to load teacher details."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  if (loading) return <LoadingState label="Loading teacher details..." />; if (error) return <ErrorState message={error} onRetry={() => void load()} />; if (!teacher) return <EmptyState title="Teacher not found" copy="This profile is unavailable." />;
  return <><button className="back-link" onClick={() => router.push("/school/teachers")}><ArrowLeft size={16} />Back to teachers</button><section className="detail-hero"><div className="detail-title"><span className="large-school-icon"><UserRound size={25} /></span><div><p className="kicker">Teacher profile</p><h2>{teacher.user?.name ?? "Teacher"}</h2><span className="code-text">{teacher.employee_id || "No employee ID"}</span></div></div><span className="status-badge status-active">School profile</span></section><section className="detail-card"><p className="kicker">Profile details</p><h3>Contact and employment</h3><div className="contact-grid"><div><Mail size={17} /><span>{teacher.user?.email || "No email"}</span></div><div><Phone size={17} /><span>{teacher.phone || "No phone"}</span></div><div><BookOpen size={17} /><span>{teacher.designation || "No designation"}</span></div><div><SchoolIcon size={17} /><span>{teacher.qualification || "No qualification"}</span></div><div className="contact-wide"><span>Joining date: {teacher.joining_date?.slice(0, 10) || "Not provided"}</span></div></div></section><section className="detail-card"><p className="kicker">Academic access</p><h3>Existing assignments</h3>{assignments.length ? <div className="assignment-list">{assignments.map((assignment) => <div key={assignment.id}><strong>{assignment.subject?.name ?? `Subject #${assignment.subject_id}`}</strong><span>{assignment.class?.name ?? `Class #${assignment.class_id}`} · {assignment.section?.name ?? `Section #${assignment.section_id}`}</span></div>)}</div> : <EmptyState title="No assignments found" copy="Assignments will appear here when configured." />}</section></>;
}
