"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { api, ApiRequestError } from "@/lib/api";
import { ConfirmDialog } from "@/components/admin/ConfirmDialog";
import { EmptyState, ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";
import { DataTable } from "@/components/admin/DataTable";
import { TeacherForm, type TeacherFormValues } from "@/components/admin/TeacherForm";
import type { Teacher, User } from "@/types";

export default function TeachersPage() {
  const router = useRouter();
  const [teachers, setTeachers] = useState<Teacher[]>([]); const [users, setUsers] = useState<User[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<Teacher | null>(null); const [modal, setModal] = useState(false); const [confirm, setConfirm] = useState<Teacher | null>(null); const [busy, setBusy] = useState(false); const [errors, setErrors] = useState<Record<string, string[]> | undefined>(); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [teacherResult, userResult] = await Promise.all([api.get<{ teachers: Teacher[] }>("/teachers"), api.get<{ users: User[] }>("/users")]); setTeachers(teacherResult.teachers); setUsers(userResult.users); } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : "Unable to load teachers."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => { const query = search.toLowerCase(); return teachers.filter((teacher) => [teacher.user?.name, teacher.user?.email, teacher.employee_id].some((value) => value?.toLowerCase().includes(query))); }, [teachers, search]);
  const openCreate = () => { setSelected(null); setErrors(undefined); setModal(true); }; const openEdit = (teacher: Teacher) => { setSelected(teacher); setErrors(undefined); setModal(true); };
  async function save(values: TeacherFormValues) { setBusy(true); setErrors(undefined); const payload = { ...values, user_id: values.user_id || undefined, employee_id: values.employee_id || null, phone: values.phone || null, designation: values.designation || null, qualification: values.qualification || null, joining_date: values.joining_date || null }; try { if (selected) { const result = await api.put<{ teacher: Teacher }>(`/teachers/${selected.id}`, payload); setTeachers((current) => current.map((item) => item.id === selected.id ? result.teacher : item)); setNotice("Teacher updated successfully."); } else { const result = await api.post<{ teacher: Teacher }>("/teachers", payload); setTeachers((current) => [result.teacher, ...current]); setNotice("Teacher added successfully."); } setModal(false); } catch (cause) { setErrors({ ...(cause instanceof ApiRequestError ? cause.details?.errors : {}), _form: [cause instanceof ApiRequestError ? cause.message : "Unable to save teacher."] }); } finally { setBusy(false); } }
  async function remove() { if (!confirm) return; setBusy(true); try { await api.delete(`/teachers/${confirm.id}`); setTeachers((current) => current.filter((item) => item.id !== confirm.id)); setConfirm(null); setNotice("Teacher deleted successfully."); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : "Unable to delete teacher."); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading teachers..." />; if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  return <><section className="admin-page-heading"><div><p className="kicker">People directory</p><h2>Teachers</h2><p>Keep the teaching team and their profiles current.</p></div><button className="primary-button compact-button" onClick={openCreate}><Plus size={17} />Add teacher</button></section>{notice && <Notice message={notice} />}<section className="list-card"><div className="list-toolbar"><label className="search-input"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, email, or employee ID" aria-label="Search teachers" /></label></div>{filtered.length ? <DataTable columns={[{ label: "Teacher", key: "teacher" }, { label: "Employee ID", key: "employee" }, { label: "Phone", key: "phone" }, { label: "Designation", key: "designation" }, { label: "Joining date", key: "joining" }, { label: "Actions", key: "actions" }]} rows={filtered.map((teacher) => ({ ...teacher, teacher: <div className="school-cell"><span className="school-avatar">{teacher.user?.name.charAt(0).toUpperCase()}</span><div><strong>{teacher.user?.name ?? "Unnamed teacher"}</strong><small>{teacher.user?.email ?? "No email"}</small></div></div>, employee: <span className="code-text">{teacher.employee_id || "—"}</span>, phone: teacher.phone || "—", designation: teacher.designation || "—", joining: teacher.joining_date?.slice(0, 10) || "—", actions: <div className="row-actions"><button onClick={() => router.push(`/school/teachers/${teacher.id}`)} aria-label="View teacher"><Eye size={16} /></button><button onClick={() => openEdit(teacher)} aria-label="Edit teacher"><Pencil size={16} /></button><button className="row-danger" onClick={() => setConfirm(teacher)} aria-label="Delete teacher"><Trash2 size={16} /></button></div> }))} /> : <EmptyState title="No teachers found" copy={teachers.length ? "Try a different search." : "Add a teacher profile to begin."} />}</section>{modal && <div className="dialog-backdrop"><div className="form-dialog"><div className="dialog-header"><p className="kicker">{selected ? "Edit profile" : "New profile"}</p><h2>{selected ? "Edit teacher" : "Add a teacher"}</h2></div><TeacherForm teacher={selected} users={users} busy={busy} errors={errors} onSubmit={save} onCancel={() => setModal(false)} /></div></div>}{confirm && <ConfirmDialog title="Delete this teacher?" copy="The teacher profile and related records may be affected by backend relationships. This action cannot be undone." busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => void remove()} />}</>;
}
