"use client";

import { useEffect, useState } from "react";
import { api, ApiRequestError } from "@/lib/api";
import { EmptyState, ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";
import type { Student } from "@/types";

type Fee = { id: number; amount: string; status: string; student?: Student; feeType?: { name: string }; feeItem?: { name: string }; payments?: Array<{ amount: string }> };
type Payment = { id: number; amount: string; payment_date: string; payment_method: string; student?: Student; studentFee?: Fee };

export default function PaymentsPage() {
  const [fees, setFees] = useState<Fee[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [studentId, setStudentId] = useState(""); const [feeId, setFeeId] = useState(""); const [amount, setAmount] = useState(""); const [method, setMethod] = useState("cash"); const [students, setStudents] = useState<Student[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { Promise.all([api.get<{ student_fees: Fee[] }>("/student-fees"), api.get<{ payments: Payment[] }>("/payments"), api.get<{ students: Student[] }>("/students")]).then(([f, p, s]) => { setFees(f.student_fees); setPayments(p.payments); setStudents(s.students); }).catch((c) => setError(c instanceof ApiRequestError ? c.message : "Unable to load payments.")).finally(() => setLoading(false)); }, []);
  const selectedFees = fees.filter((fee) => String(fee.student?.id) === studentId && fee.status !== "paid");
  async function pay(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { const fee = fees.find((f) => String(f.id) === feeId); const result = await api.post<{ payment: Payment }>("/payments", { student_fee_id: Number(feeId), student_id: Number(studentId), amount, payment_date: new Date().toISOString().slice(0, 10), payment_method: method }); setPayments((p) => [result.payment, ...p]); setNotice("Payment recorded successfully."); setAmount(""); setFees((current) => current.map((f) => f.id === fee?.id ? { ...f, status: "partial" } : f)); } catch (c) { setError(c instanceof ApiRequestError ? c.message : "Unable to record payment."); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading payments..." />; if (error && !students.length) return <ErrorState message={error} onRetry={() => window.location.reload()} />;
  return <><section className="admin-page-heading"><div><p className="kicker">Finance workspace</p><h2>Payments</h2><p>Record payments and review due/payment history.</p></div></section>{notice && <Notice message={notice} />}{error && <p className="field-error">{error}</p>}<section className="list-card"><h3>Quick Payment</h3><form className="school-form" onSubmit={pay}><div className="form-grid"><label>Student<select value={studentId} onChange={(e) => { setStudentId(e.target.value); setFeeId(""); }} required><option value="">Select student</option>{students.map((s) => <option key={s.id} value={s.id}>{s.student_id ?? s.id} · {s.user?.name}</option>)}</select></label><label>Due<select value={feeId} onChange={(e) => setFeeId(e.target.value)} required><option value="">Select due</option>{selectedFees.map((f) => <option key={f.id} value={f.id}>{f.feeItem?.name ?? f.feeType?.name} · {f.amount}</option>)}</select></label><label>Amount<input value={amount} onChange={(e) => setAmount(e.target.value)} inputMode="decimal" required /></label><label>Payment method<select value={method} onChange={(e) => setMethod(e.target.value)}><option value="cash">Cash</option><option value="bank">Bank</option><option value="mobile_banking">Mobile banking</option><option value="other">Other</option></select></label></div><button className="primary-button" disabled={busy}>{busy ? "Saving..." : "Record payment"}</button></form></section><section className="list-card"><h3>Payment List</h3>{payments.length ? payments.map((p) => <div className="list-toolbar" key={p.id}><span>{p.student?.user?.name} · {p.studentFee?.feeItem?.name ?? p.studentFee?.feeType?.name}</span><span>{p.amount} · {p.payment_method} · {p.payment_date}</span></div>) : <EmptyState title="No payments" copy="Payments will appear here." />}</section><section className="list-card"><h3>Due List</h3>{fees.length ? fees.map((f) => { const paid = f.payments?.reduce((sum, item) => sum + Number(item.amount), 0) ?? 0; return <div className="list-toolbar" key={f.id}><span>{f.student?.user?.name} · {f.feeItem?.name ?? f.feeType?.name}</span><span>Total {f.amount} · Paid {paid.toFixed(2)} · Due {(Number(f.amount) - paid).toFixed(2)}</span></div>; }) : <EmptyState title="No dues" copy="Student dues will appear here." />}</section></>;
}
