"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Link2, Mail, Phone, UserRound, X } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { api, ApiRequestError } from "@/lib/api";
import { EmptyState, ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";
import type { Parent, Student } from "@/types";
export default function ParentDetailsPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [parent, setParent] = useState<Parent | null>(null); const [students, setStudents] = useState<Student[]>([]); const [studentId, setStudentId] = useState(""); const [relationship, setRelationship] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [parentResult, studentResult] = await Promise.all([api.get<{ parent: Parent }>(`/parents/${id}`), api.get<{ students: Student[] }>("/students")]); setParent(parentResult.parent); setStudents(studentResult.students); } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : "Unable to load parent details."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const available = useMemo(() => students.filter((student) => !parent?.children?.some((child) => child.id === student.id)), [students, parent]);
  async function attach() { if (!studentId) return; setBusy(true); try { const result = await api.post<{ parent: Parent }>(`/parents/${id}/students`, { student_id: Number(studentId), relationship: relationship || null }); setParent(result.parent); setStudentId(""); setRelationship(""); setNotice("Student linked successfully."); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : "Unable to link student."); } finally { setBusy(false); } }
  async function detach(student: Student) { setBusy(true); try { await api.delete(`/parents/${id}/students/${student.id}`); setParent((current) => current ? { ...current, children: current.children?.filter((child) => child.id !== student.id) } : current); setNotice("Student removed successfully."); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : "Unable to remove student."); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading parent details..." />; if (error) return <ErrorState message={error} onRetry={() => void load()} />; if (!parent) return <EmptyState title="Parent not found" copy="This profile is unavailable." />;
  return <><button className="back-link" onClick={() => router.push("/school/parents")}><ArrowLeft size={16} />Back to parents</button>{notice && <Notice message={notice} />}<section className="detail-hero"><div className="detail-title"><span className="large-school-icon"><UserRound size={25} /></span><div><p className="kicker">Parent profile</p><h2>{parent.name}</h2><span className="code-text">{parent.email}</span></div></div><span className="status-badge status-active">Parent account</span></section><section className="detail-card"><p className="kicker">Contact</p><h3>Account information</h3><div className="contact-grid"><div><Mail size={17} /><span>{parent.email}</span></div><div><Phone size={17} /><span>No phone provided</span></div></div></section><section className="detail-card"><p className="kicker">Family links</p><h3>Linked children</h3>{parent.children?.length ? <div className="assignment-list">{parent.children.map((child) => <div key={child.id}><strong>{child.user?.name ?? `Student #${child.id}`}</strong><span>{child.class?.name ?? "Unassigned"} · <button className="inline-remove" onClick={() => void detach(child)} disabled={busy} aria-label={`Remove ${child.user?.name ?? "student"}`}><X size={14} />Remove</button></span></div>)}</div> : <EmptyState title="No linked children" copy="Link a student below to make this relationship available." />}<div className="link-form"><select value={studentId} onChange={(event) => setStudentId(event.target.value)} aria-label="Student to link"><option value="">Select a student</option>{available.map((student) => <option key={student.id} value={student.id}>{student.user?.name ?? `Student #${student.id}`}</option>)}</select><input value={relationship} onChange={(event) => setRelationship(event.target.value)} placeholder="Relationship (optional)" aria-label="Relationship" /><button className="primary-button" onClick={() => void attach()} disabled={busy || !studentId}><Link2 size={16} />{busy ? "Saving..." : "Link student"}</button></div></section></>;
}
