"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Filter, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { api, ApiRequestError } from "@/lib/api";
import { SectionForm, type SectionFormValues } from "@/components/admin/SectionForm";
import { ConfirmDialog } from "@/components/admin/ConfirmDialog";
import { DataTable } from "@/components/admin/DataTable";
import { EmptyState, ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";
import type { SchoolClass, Section } from "@/types";
export default function SectionsPage() {
  const [items, setItems] = useState<Section[]>([]); const [classes, setClasses] = useState<SchoolClass[]>([]); const [search, setSearch] = useState(""); const [classFilter, setClassFilter] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<Section | null>(null); const [confirm, setConfirm] = useState<Section | null>(null); const [modal, setModal] = useState(false); const [busy, setBusy] = useState(false); const [errors, setErrors] = useState<Record<string, string[]> | undefined>(); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [sections, classResult] = await Promise.all([api.get<{ sections: Section[] }>("/sections"), api.get<{ classes: SchoolClass[] }>("/classes")]); setItems(sections.sections); setClasses(classResult.classes); } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : "Unable to load sections."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => items.filter((item) => { const query = search.toLowerCase(); return (!query || item.name.toLowerCase().includes(query) || item.schoolClass?.name.toLowerCase().includes(query)) && (!classFilter || String(item.school_class_id) === classFilter); }), [items, search, classFilter]);
  async function save(values: SectionFormValues) { setBusy(true); setErrors(undefined); try { const result = selected ? await api.put<{ section: Section }>(`/sections/${selected.id}`, values) : await api.post<{ section: Section }>("/sections", values); setItems((current) => selected ? current.map((item) => item.id === selected.id ? result.section : item) : [result.section, ...current]); setModal(false); setNotice(selected ? "Section updated successfully." : "Section added successfully."); } catch (cause) { setErrors({ ...(cause instanceof ApiRequestError ? cause.details?.errors : {}), _form: [cause instanceof ApiRequestError ? cause.message : "Unable to save section."] }); } finally { setBusy(false); } }
  async function remove() { if (!confirm) return; setBusy(true); try { await api.delete(`/sections/${confirm.id}`); setItems((current) => current.filter((item) => item.id !== confirm.id)); setConfirm(null); setNotice("Section deleted successfully."); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : "Unable to delete section."); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading sections..." />; if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  return <><section className="admin-page-heading"><div><p className="kicker">Academic setup</p><h2>Sections</h2><p>Divide classes into manageable groups and cohorts.</p></div><button className="primary-button compact-button" onClick={() => { setSelected(null); setErrors(undefined); setModal(true); }}><Plus size={17} />Add section</button></section>{notice && <Notice message={notice} />}<section className="list-card"><div className="list-toolbar"><label className="search-input"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search section or class" aria-label="Search sections" /></label><label className="filter-select"><Filter size={16} /><select value={classFilter} onChange={(event) => setClassFilter(event.target.value)} aria-label="Filter by class"><option value="">All classes</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>{filtered.length ? <DataTable columns={[{ label: "Section", key: "name" }, { label: "Class", key: "class" }, { label: "Status", key: "status" }, { label: "Actions", key: "actions" }]} rows={filtered.map((item) => ({ ...item, name: <strong>{item.name}</strong>, class: item.schoolClass?.name || `Class #${item.school_class_id}`, status: <span className={`status-badge ${item.is_active === false ? "status-inactive" : "status-active"}`}>{item.is_active === false ? "Inactive" : "Active"}</span>, actions: <div className="row-actions"><button onClick={() => { setSelected(item); setErrors(undefined); setModal(true); }} aria-label={`Edit ${item.name}`}><Pencil size={16} /></button><button className="row-danger" onClick={() => setConfirm(item)} aria-label={`Delete ${item.name}`}><Trash2 size={16} /></button></div> }))} /> : <EmptyState title="No sections found" copy={items.length ? "Try a different search or class filter." : "Add your first section to begin."} />}</section>{modal && <div className="dialog-backdrop"><div className="form-dialog"><div className="dialog-header"><p className="kicker">{selected ? "Edit record" : "New record"}</p><h2>{selected ? "Edit section" : "Add a section"}</h2></div><SectionForm section={selected} classes={classes} busy={busy} errors={errors} onSubmit={save} onCancel={() => setModal(false)} /></div></div>}{confirm && <ConfirmDialog title={`Delete ${confirm.name}?`} copy="Sections with related students or academic records may be rejected by backend relationships." busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => void remove()} />}</>;
}
