"use client";

import { useCallback, useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { api, ApiRequestError } from "@/lib/api";
import { ConfirmDialog } from "@/components/admin/ConfirmDialog";
import { DataTable } from "@/components/admin/DataTable";
import { EmptyState, ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";
import type { SchoolClass, Section, Subject } from "@/types";

type Assignment = { id: number; school_class_id: number; section_id?: number; subject_id?: number; schoolClass?: SchoolClass; section?: Section; subject?: Subject };
export function AcademicAssignmentPage({ subjectMode = false }: { subjectMode?: boolean }) {
  const [items, setItems] = useState<Assignment[]>([]); const [classes, setClasses] = useState<SchoolClass[]>([]); const [sections, setSections] = useState<Section[]>([]); const [subjects, setSubjects] = useState<Subject[]>([]); const [classId, setClassId] = useState(""); const [targetId, setTargetId] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState<Assignment | null>(null); const [notice, setNotice] = useState("");
  const endpoint = subjectMode ? "class-subject-assignments" : "class-section-assignments";
  const load = useCallback(async () => { setLoading(true); setError(""); try { const classResult = await api.get<{ classes: SchoolClass[] }>("/classes"); const assignmentResult = await api.get<{ assignments: Assignment[] }>(`/${endpoint}`); setClasses(classResult.classes); setItems(assignmentResult.assignments); if (subjectMode) { const targetResult = await api.get<{ subjects: Subject[] }>("/subjects"); setSubjects(targetResult.subjects); } else { const targetResult = await api.get<{ sections: Section[] }>("/sections"); setSections(targetResult.sections); } } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : "Unable to load assignments."); } finally { setLoading(false); } }, [endpoint, subjectMode]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function assign() { if (!classId || !targetId) return; setBusy(true); try { const payload = subjectMode ? { school_class_id: Number(classId), subject_id: Number(targetId) } : { school_class_id: Number(classId), section_id: Number(targetId) }; const result = await api.post<{ assignment: Assignment }>(`/${endpoint}`, payload); setItems((current) => [result.assignment, ...current]); setClassId(""); setTargetId(""); setNotice("Assignment created successfully."); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : "Unable to create assignment."); } finally { setBusy(false); } }
  async function remove() { if (!confirm) return; setBusy(true); try { await api.delete(`/${endpoint}/${confirm.id}`); setItems((current) => current.filter((item) => item.id !== confirm.id)); setConfirm(null); setNotice("Assignment removed successfully."); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : "Unable to remove assignment."); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading assignments..." />; if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  const targetOptions = subjectMode ? subjects : sections;
  return <><section className="admin-page-heading"><div><p className="kicker">Academic setup</p><h2>{subjectMode ? "Subject Assign To Class" : "Section Assign To Class"}</h2><p>Keep relationships inside your school and prevent duplicate assignments.</p></div></section>{notice && <Notice message={notice} />}<section className="list-card"><div className="form-grid"><label>Class<select value={classId} onChange={(event) => setClassId(event.target.value)}><option value="">Select class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{subjectMode ? "Subject" : "Section"}<select value={targetId} onChange={(event) => setTargetId(event.target.value)}><option value="">Select {subjectMode ? "subject" : "section"}</option>{targetOptions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="primary-button compact-button" onClick={() => void assign()} disabled={busy || !classId || !targetId}><Plus size={17} />Assign</button></div>{items.length ? <DataTable columns={[{ label: "Class", key: "class" }, { label: subjectMode ? "Subject" : "Section", key: "target" }, { label: "Actions", key: "actions" }]} rows={items.map((item) => ({ ...item, class: item.schoolClass?.name || `Class #${item.school_class_id}`, target: subjectMode ? item.subject?.name || `Subject #${item.subject_id}` : item.section?.name || `Section #${item.section_id}`, actions: <button className="row-danger" onClick={() => setConfirm(item)} aria-label="Remove assignment"><Trash2 size={16} /></button> }))} /> : <EmptyState title="No assignments found" copy="Create the first assignment above." />}</section>{confirm && <ConfirmDialog title="Remove this assignment?" copy="The related class and academic record will remain unchanged." busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => void remove()} />}</>;
}
