"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Search, Trash2 } from "lucide-react";
import { api, ApiRequestError } from "@/lib/api";
import { ConfirmDialog } from "@/components/admin/ConfirmDialog";
import { DataTable } from "@/components/admin/DataTable";
import { EmptyState, ErrorState, LoadingState, Notice } from "@/components/admin/AdminStates";

type Value = string | number | boolean | null | undefined;
type RecordItem = { id: number; name: string; is_active?: boolean; [key: string]: Value };
export type AcademicField = { key: string; label: string; type?: "text" | "time" | "date" | "number" | "checkbox"; required?: boolean };

export function AcademicCrudPage({ title, description, endpoint, responseKey, fields, columns = ["name"], itemLabel = title.slice(0, -1), singularKey }: { title: string; description: string; endpoint: string; responseKey: string; fields: AcademicField[]; columns?: string[]; itemLabel?: string; singularKey?: string }) {
  const [items, setItems] = useState<RecordItem[]>([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [selected, setSelected] = useState<RecordItem | null>(null);
  const [confirm, setConfirm] = useState<RecordItem | null>(null);
  const [busy, setBusy] = useState(false);
  const [modal, setModal] = useState(false);
  const [errors, setErrors] = useState<Record<string, string[]> | undefined>();
  const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await api.get<Record<string, RecordItem[]>>(`/${endpoint}`); setItems(result[responseKey] ?? []); } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : `Unable to load ${title.toLowerCase()}.`); } finally { setLoading(false); } }, [endpoint, responseKey, title]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => items.filter((item) => { const query = search.toLowerCase(); return !query || Object.values(item).some((value) => String(value ?? "").toLowerCase().includes(query)); }), [items, search]);
  const openCreate = () => { setSelected(null); setErrors(undefined); setModal(true); };
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setErrors(undefined); const form = new FormData(event.currentTarget); const payload: Record<string, Value> = {}; fields.forEach((field) => { const raw = form.get(field.key); const value = field.type === "checkbox" ? raw === "on" : typeof raw === "string" ? raw : null; payload[field.key] = field.type === "number" ? (value ? Number(value) : null) : value; }); try { const result = selected ? await api.put<Record<string, RecordItem>>(`/${endpoint}/${selected.id}`, payload) : await api.post<Record<string, RecordItem>>(`/${endpoint}`, payload); const item = result[singularKey ?? (endpoint.endsWith("s") ? endpoint.slice(0, -1) : endpoint)] ?? result[responseKey]?.[0]; if (item) setItems((current) => selected ? current.map((entry) => entry.id === selected.id ? item : entry) : [item, ...current]); setModal(false); setNotice(`${itemLabel} ${selected ? "updated" : "added"} successfully.`); } catch (cause) { setErrors({ ...(cause instanceof ApiRequestError ? cause.details?.errors : {}), _form: [cause instanceof ApiRequestError ? cause.message : `Unable to save ${itemLabel.toLowerCase()}.`] }); } finally { setBusy(false); } }
  async function remove() { if (!confirm) return; setBusy(true); try { await api.delete(`/${endpoint}/${confirm.id}`); setItems((current) => current.filter((item) => item.id !== confirm.id)); setConfirm(null); setNotice(`${itemLabel} deleted successfully.`); } catch (cause) { setNotice(cause instanceof ApiRequestError ? cause.message : `Unable to delete ${itemLabel.toLowerCase()}.`); } finally { setBusy(false); } }
  if (loading) return <LoadingState label={`Loading ${title.toLowerCase()}...`} />;
  if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  return <><section className="admin-page-heading"><div><p className="kicker">Academic setup</p><h2>{title}</h2><p>{description}</p></div><button className="primary-button compact-button" onClick={openCreate}><Plus size={17} />Add {itemLabel.toLowerCase()}</button></section>{notice && <Notice message={notice} />}<section className="list-card"><div className="list-toolbar"><label className="search-input"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${title.toLowerCase()}`} aria-label={`Search ${title.toLowerCase()}`} /></label></div>{filtered.length ? <DataTable columns={[...columns.map((key) => ({ label: fields.find((field) => field.key === key)?.label ?? key, key })), { label: "Status", key: "status" }, { label: "Actions", key: "actions" }]} rows={filtered.map((item) => ({ ...item, status: <span className={`status-badge ${item.is_active === false ? "status-inactive" : "status-active"}`}>{item.is_active === false ? "Inactive" : "Active"}</span>, actions: <div className="row-actions"><button onClick={() => { setSelected(item); setErrors(undefined); setModal(true); }} aria-label={`Edit ${item.name}`}><Pencil size={16} /></button><button className="row-danger" onClick={() => setConfirm(item)} aria-label={`Delete ${item.name}`}><Trash2 size={16} /></button></div> }))} /> : <EmptyState title={`No ${title.toLowerCase()} found`} copy={items.length ? "Try a different search." : `Add your first ${itemLabel.toLowerCase()} to begin.`} />}</section>{modal && <div className="dialog-backdrop"><div className="form-dialog"><div className="dialog-header"><p className="kicker">{selected ? "Edit record" : "New record"}</p><h2>{selected ? `Edit ${itemLabel.toLowerCase()}` : `Add ${itemLabel.toLowerCase()}`}</h2></div><form className="school-form" onSubmit={save}><div className="form-grid">{fields.map((field) => <label key={field.key}>{field.label}<input name={field.key} type={field.type === "checkbox" ? "checkbox" : field.type ?? "text"} defaultValue={field.type === "checkbox" ? undefined : String(selected?.[field.key] ?? "")} defaultChecked={field.type === "checkbox" ? Boolean(selected?.[field.key] ?? true) : undefined} required={field.required} />{errors?.[field.key] && <small className="field-error">{errors[field.key][0]}</small>}</label>)}</div>{errors?._form && <div className="form-error">{errors._form[0]}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={() => setModal(false)}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? "Saving..." : selected ? "Save changes" : `Add ${itemLabel.toLowerCase()}`}</button></div></form></div></div>}{confirm && <ConfirmDialog title={`Delete ${confirm.name}?`} copy="Related academic records may prevent deletion." busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => void remove()} />}</>;
}
