import { FormEvent, useState } from "react";
import type { SchoolClass } from "@/types";
export interface ClassFormValues { name: string; code: string; numeric_order: string; is_active: boolean; }
export function ClassForm({ schoolClass, busy, errors, onSubmit, onCancel }: { schoolClass?: SchoolClass | null; busy: boolean; errors?: Record<string, string[]>; onSubmit: (values: ClassFormValues) => void; onCancel: () => void }) {
  const [values, setValues] = useState<ClassFormValues>({ name: schoolClass?.name ?? "", code: schoolClass?.code ?? "", numeric_order: schoolClass?.numeric_order?.toString() ?? "", is_active: schoolClass?.is_active ?? true });
  const set = (key: keyof ClassFormValues, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }));
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!values.name.trim()) return; onSubmit(values); }
  return <form className="school-form" onSubmit={submit}><div className="form-grid"><label>Class name<input value={values.name} onChange={(event) => set("name", event.target.value)} required />{errors?.name && <small className="field-error">{errors.name[0]}</small>}</label><label>Code<input value={values.code} onChange={(event) => set("code", event.target.value)} />{errors?.code && <small className="field-error">{errors.code[0]}</small>}</label><label>Display order<input type="number" min="1" value={values.numeric_order} onChange={(event) => set("numeric_order", event.target.value)} />{errors?.numeric_order && <small className="field-error">{errors.numeric_order[0]}</small>}</label><label className="check-label"><input type="checkbox" checked={values.is_active} onChange={(event) => set("is_active", event.target.checked)} />Active class</label></div>{errors?._form && <div className="form-error">{errors._form[0]}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? "Saving..." : schoolClass ? "Save changes" : "Add class"}</button></div></form>;
}
