import { FormEvent, useState } from "react";
import type { School } from "@/types";

export interface SchoolFormValues { name: string; code: string; email: string; phone: string; address: string; logo: string; is_active: boolean; admin_name: string; admin_email: string; admin_password: string; }
const empty: SchoolFormValues = { name: "", code: "", email: "", phone: "", address: "", logo: "", is_active: true, admin_name: "", admin_email: "", admin_password: "" };

export function SchoolForm({ school, busy, errors, onSubmit, onCancel }: { school?: School | null; busy: boolean; errors?: Record<string, string[]>; onSubmit: (values: SchoolFormValues) => void; onCancel: () => void }) {
  const [values, setValues] = useState<SchoolFormValues>(() => school ? { name: school.name, code: school.code, email: school.email ?? "", phone: school.phone ?? "", address: school.address ?? "", logo: school.logo ?? "", is_active: school.is_active ?? true, admin_name: "", admin_email: "", admin_password: "" } : empty);
  const set = (key: keyof SchoolFormValues, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }));
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!values.name.trim() || !values.code.trim() || (!school && (!values.admin_name.trim() || !values.admin_email.trim() || !values.admin_password))) return; onSubmit(values); }
  return <form className="school-form" onSubmit={submit}><div className="form-grid"><label>School name<input value={values.name} onChange={(event) => set("name", event.target.value)} required />{errors?.name && <small className="field-error">{errors.name[0]}</small>}</label><label>School code<input value={values.code} onChange={(event) => set("code", event.target.value)} required />{errors?.code && <small className="field-error">{errors.code[0]}</small>}</label><label>Email<input type="email" value={values.email} onChange={(event) => set("email", event.target.value)} />{errors?.email && <small className="field-error">{errors.email[0]}</small>}</label><label>Phone<input value={values.phone} onChange={(event) => set("phone", event.target.value)} />{errors?.phone && <small className="field-error">{errors.phone[0]}</small>}</label><label className="wide-field">Address<textarea value={values.address} onChange={(event) => set("address", event.target.value)} rows={3} />{errors?.address && <small className="field-error">{errors.address[0]}</small>}</label>{!school && <><label>Admin name<input value={values.admin_name} onChange={(event) => set("admin_name", event.target.value)} required />{errors?.admin_name && <small className="field-error">{errors.admin_name[0]}</small>}</label><label>Admin email<input type="email" value={values.admin_email} onChange={(event) => set("admin_email", event.target.value)} required />{errors?.admin_email && <small className="field-error">{errors.admin_email[0]}</small>}</label><label className="wide-field">Admin password<input type="password" value={values.admin_password} onChange={(event) => set("admin_password", event.target.value)} minLength={8} required />{errors?.admin_password && <small className="field-error">{errors.admin_password[0]}</small>}</label></>}<label className="wide-field">Logo URL<input value={values.logo} onChange={(event) => set("logo", event.target.value)} placeholder="Optional image URL" />{errors?.logo && <small className="field-error">{errors.logo[0]}</small>}</label><label className="check-label wide-field"><input type="checkbox" checked={values.is_active} onChange={(event) => set("is_active", event.target.checked)} />Active school</label></div>{errors?._form && <div className="form-error">{errors._form[0]}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button><button type="submit" className="primary-button" disabled={busy}>{busy ? "Saving..." : school ? "Save changes" : "Create school"}</button></div></form>;
}