import { FormEvent, useState } from "react";
import type { Subject } from "@/types";
export interface SubjectFormValues { name: string; code: string; description: string; is_active: boolean; }
export function SubjectForm({ subject, busy, errors, onSubmit, onCancel }: { subject?: Subject | null; busy: boolean; errors?: Record<string, string[]>; onSubmit: (values: SubjectFormValues) => void; onCancel: () => void }) {
  const [values, setValues] = useState<SubjectFormValues>({ name: subject?.name ?? "", code: subject?.code ?? "", description: subject?.description ?? "", is_active: subject?.is_active ?? true });
  const set = (key: keyof SubjectFormValues, value: string | boolean) => setValues((current) => ({ ...current, [key]: value }));
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!values.name.trim() || !values.code.trim()) return; onSubmit(values); }
  return <form className="school-form" onSubmit={submit}><div className="form-grid"><label>Subject name<input value={values.name} onChange={(event) => set("name", event.target.value)} required />{errors?.name && <small className="field-error">{errors.name[0]}</small>}</label><label>Subject code<input value={values.code} onChange={(event) => set("code", event.target.value)} required />{errors?.code && <small className="field-error">{errors.code[0]}</small>}</label><label className="wide-field">Description<textarea rows={3} value={values.description} onChange={(event) => set("description", event.target.value)} />{errors?.description && <small className="field-error">{errors.description[0]}</small>}</label><label className="check-label"><input type="checkbox" checked={values.is_active} onChange={(event) => set("is_active", event.target.checked)} />Active subject</label></div>{errors?._form && <div className="form-error">{errors._form[0]}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? "Saving..." : subject ? "Save changes" : "Add subject"}</button></div></form>;
}
