import { FormEvent, useState } from "react";
import type { Teacher, User } from "@/types";

export interface TeacherFormValues { user_id: number | ""; employee_id: string; phone: string; designation: string; qualification: string; joining_date: string; }
const empty: TeacherFormValues = { user_id: "", employee_id: "", phone: "", designation: "", qualification: "", joining_date: "" };

export function TeacherForm({ teacher, users, busy, errors, onSubmit, onCancel }: { teacher?: Teacher | null; users: User[]; busy: boolean; errors?: Record<string, string[]>; onSubmit: (values: TeacherFormValues) => void; onCancel: () => void }) {
  const [values, setValues] = useState<TeacherFormValues>(() => teacher ? { user_id: teacher.user_id, employee_id: teacher.employee_id ?? "", phone: teacher.phone ?? "", designation: teacher.designation ?? "", qualification: teacher.qualification ?? "", joining_date: teacher.joining_date?.slice(0, 10) ?? "" } : empty);
  const set = (key: keyof TeacherFormValues, value: string | number) => setValues((current) => ({ ...current, [key]: value }));
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!values.user_id && !teacher) return; onSubmit(values); }
  return <form className="school-form" onSubmit={submit}><div className="form-grid"><label className="wide-field">Teacher account{teacher ? <input value={teacher.user?.name ?? `User #${teacher.user_id}`} disabled /> : <select value={values.user_id} onChange={(event) => set("user_id", event.target.value ? Number(event.target.value) : "")} required><option value="">Select a teacher account</option>{users.filter((user) => user.role === "teacher").map((user) => <option key={user.id} value={user.id}>{user.name} · {user.email}</option>)}</select>}{errors?.user_id && <small className="field-error">{errors.user_id[0]}</small>}</label><label>Employee ID<input value={values.employee_id} onChange={(event) => set("employee_id", event.target.value)} /></label><label>Phone<input value={values.phone} onChange={(event) => set("phone", event.target.value)} /></label><label>Designation<input value={values.designation} onChange={(event) => set("designation", event.target.value)} /></label><label>Qualification<input value={values.qualification} onChange={(event) => set("qualification", event.target.value)} /></label><label>Joining date<input type="date" value={values.joining_date} onChange={(event) => set("joining_date", event.target.value)} /></label></div>{errors?._form && <div className="form-error">{errors._form[0]}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button><button type="submit" className="primary-button" disabled={busy}>{busy ? "Saving..." : teacher ? "Save changes" : "Add teacher"}</button></div></form>;
}
